version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  mongo:
    image: mongo:8.0.3-noble
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
  app:
    image: ghcr.io/czer0c/simple-node:main  # Using the pre-built image from GHCR
    container_name: simple-node-app
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
    environment:
      - NODE_ENV=production  # You can set environment variables as needed
    restart: unless-stopped
volumes:
  mongo-data:
  postgres-data: