version: '3.8'

services:
  # mongo:
  #   image: mongo:8.0.3-noble
  #   volumes:
  #     - mongo-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   ports:
  #     - "27017:27017"
  app:
    image: ghcr.io/czer0c/simple-node:main  # Using the pre-built image from GHCR
    container_name: simple-node-app
    ports:
      - '${SERVICE_PORT}:${SERVICE_PORT}'
      # - "5000:5000"  # Map port 5000 inside the container to port 5000 on the host
    environment:
      - NODE_ENV=production  # You can set environment variables as needed
    restart: unless-stopped
# volumes:
#   mongo-data:

# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     environment:
#       NODE_ENV: development